#! /bin/sh
#  _                                 
# | |__  ___ _ ____      ___ __ ___  
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \ 
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#           |_|

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
$HOME/.config/picom.conf

bspc monitor -d I II III IV V

bspc config border_width        1
bspc config window_gap          8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
#bspc config gapless_monocle      true
bspc config single_monocle	 true
bspc config ignore_ewmh_focus	 true

#bspc config focused_border_color "#dedbd9"
bspc config focused_border_color "#f9f5f7"
bspc config normal_border_color "#b8a3bc"

#mouse focus
bspc config focus_follows_pointer true
xinput set-prop 11 317 1 &
libinput-gestures-setup start &

#autostart
nitrogen --restore &
picom &
dunst &
slack -u &


bspc rule -a slack -o desktop='^4'
bspc rule -a whatsdesk -o desktop='^4'
bspc rule -a AndroidMessages -o desktop='^4'
bspc rule -a teams -o desktop='^5'
bspc rule -a spotify -o desktop='^3'
bspc rule -a firefox -o desktop='^2'
